% Make graphics

fulldataAUC = repmat(mean(FAUC),4);

figure;
hold on;
plotfull = plot (perc,fulldataAUC);
for i=1:1:length(method)
   plotmethod{i}=plot(perc,mean(AUC(:,i,:)));
end

hTitle  = title ('Comparison between methods');
hXLabel = xlabel('Imbalance');
hYLabel = ylabel('AUC');
% method legeng
hLegend = legend( ...
  [plotfull, plotmethod{1}, plotmethod{2}, plotmethod{3}, plotmethod{4},...
  plotmethod{5},plotmethod{6},plotmethod{7},], ...
  'Ref'      , ...
  'remove'   , ...
  'mean'     , ...
  'median'   , ...
  'linear'   , ...
  'quadratic', ...
  'hot-deck' , ...
  'knn');
% print_name=strcat(pathh, name, '.eps');
% print('-depsc', print_name)
