function [SUBJECT_ID,ICUSTAY_ID,HADM_ID,ICUSTAY_INTIME,MIN_POST_ADM,VAL,UNIT,DATATYPE] = ImportCsvDataFile(filename, startRow, endRow)
%IMPORTCSVDATAFILE Import numeric data from a text file as column vectors.
%   [SUBJECT_ID,ICUSTAY_ID,HADM_ID,ICUSTAY_INTIME,MIN_POST_ADM,VAL,UNIT,DATATYPE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [SUBJECT_ID,ICUSTAY_ID,HADM_ID,ICUSTAY_INTIME,MIN_POST_ADM,VAL,UNIT,DATATYPE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [SUBJECT_ID,ICUSTAY_ID,HADM_ID,ICUSTAY_INTIME,MIN_POST_ADM,VAL,UNIT,DATATYPE]
%   = importfile('export_albumin.csv',2, 711);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/06/24 09:37:31

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,5,6,8]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,5,6,8]);
rawCellColumns = raw(:, [4,7]);


%% Allocate imported array to column variable names
SUBJECT_ID = cell2mat(rawNumericColumns(:, 1));
ICUSTAY_ID = cell2mat(rawNumericColumns(:, 2));
HADM_ID = cell2mat(rawNumericColumns(:, 3));
ICUSTAY_INTIME = rawCellColumns(:, 1);
MIN_POST_ADM = cell2mat(rawNumericColumns(:, 4));
VAL = cell2mat(rawNumericColumns(:, 5));
UNIT = rawCellColumns(:, 2);
DATATYPE = cell2mat(rawNumericColumns(:, 6));

