function [SUBJECT_ID1,HADM_ID1,ICUSTAY_ID1,SUBJECT_ICUSTAY_TOTAL_NUM,DOB,ICUSTAY_INTIME1,ICUSTAY_OUTTIME,DOD,MINSTODISCHARGE,GENDER,WEIGHT_FIRST,HEIGHT,AGE,ILOS,CAREUNIT,SERVTYPE,MORT_ICU] = ImportDemographicFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [SUBJECT_ID1,HADM_ID1,ICUSTAY_ID1,SUBJECT_ICUSTAY_TOTAL_NUM,DOB,ICUSTAY_INTIME1,ICUSTAY_OUTTIME,DOD,MINSTODISCHARGE,GENDER,WEIGHT_FIRST,HEIGHT,AGE,ILOS,CAREUNIT,SERVTYPE,MORT_ICU]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [SUBJECT_ID1,HADM_ID1,ICUSTAY_ID1,SUBJECT_ICUSTAY_TOTAL_NUM,DOB,ICUSTAY_INTIME1,ICUSTAY_OUTTIME,DOD,MINSTODISCHARGE,GENDER,WEIGHT_FIRST,HEIGHT,AGE,ILOS,CAREUNIT,SERVTYPE,MORT_ICU]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [SUBJECT_ID1,HADM_ID1,ICUSTAY_ID1,SUBJECT_ICUSTAY_TOTAL_NUM,DOB,ICUSTAY_INTIME1,ICUSTAY_OUTTIME,DOD,MINSTODISCHARGE,GENDER,WEIGHT_FIRST,HEIGHT,AGE,ILOS,CAREUNIT,SERVTYPE,MORT_ICU]
%   = importfile('export_demog.csv',2, 661);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/06/24 09:49:26

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: double (%f)
%	column10: text (%s)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: text (%s)
%	column16: text (%s)
%   column17: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%s%s%s%s%f%s%f%f%f%f%s%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
SUBJECT_ID1 = dataArray{:, 1};
HADM_ID1 = dataArray{:, 2};
ICUSTAY_ID1 = dataArray{:, 3};
SUBJECT_ICUSTAY_TOTAL_NUM = dataArray{:, 4};
DOB = dataArray{:, 5};
ICUSTAY_INTIME1 = dataArray{:, 6};
ICUSTAY_OUTTIME = dataArray{:, 7};
DOD = dataArray{:, 8};
MINSTODISCHARGE = dataArray{:, 9};
GENDER = dataArray{:, 10};
WEIGHT_FIRST = dataArray{:, 11};
HEIGHT = dataArray{:, 12};
AGE = dataArray{:, 13};
ILOS = dataArray{:, 14};
CAREUNIT = dataArray{:, 15};
SERVTYPE = dataArray{:, 16};
MORT_ICU = dataArray{:, 17};

